apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcpspark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gcp-spark-role
subjects:
  - kind: ServiceAccount
    name: gcpspark
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---